server.port: 8081
spring:
  h2.console.enabled: true
  h2.console.path: "/db-console"

  datasource:
    #pooled: true
    #dbCreate: create-drop
    name: gorm
    url: jdbc:h2:mem:gorm
    driverClassName: org.h2.Driver
    username: sa
    password:

hibernate:
  hbm2ddl.auto: create-drop
  show_sql: true
  format_sql: true
  naming_strategy: ns.gflex.util.PrefixedNamingStrategy


#spring-boot-1.5.4.RELEASE.jar!/org/springframework/boot/logging/logback/base.xml
#org.springframework.boot.logging.logback.DefaultLogbackConfiguration
#https://logback.qos.ch/manual/layouts.html
#https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-logging.html
logging:
  file: "gflex-reboot.log"
  pattern.console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID}){magenta} %clr(---){faint} %clr([%t]){faint} %clr(%-60.60logger{59}){cyan} %clr(:){faint} %m%n    %caller{1}${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  pattern.file: "%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:%5p} ${PID} --- [%t] %-40.40logger{39} : %m%n    %caller{1}${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  pattern.level: "%5p"
  level:
    org.hibernate: INFO
    ns.gflex: DEBUG
    org.hibernate.engine.transaction: DEBUG
    org.apache.flex.blazeds.Message.RPC: INFO
    org.apache.flex.blazeds: DEBUG